AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - CustomResourceUpdaterMacro

Description: >
  Test Stack for Custom Resource Updater

Resources:
  customresource_name:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:135637915716:function:custom-resource-demo     # require
