AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - CustomResourceUpdaterMacro

Description: >
  Test Stack for Custom Resource Updater

Resources:
  customresource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: arn:aws:lambda:REGION:ACCT_ID:function:custom-resource-demo    
  customresource2:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: arn:aws:lambda:REGION:ACCT_ID:function:custom-resource-demo

ResourcesToUpdate:
  - customresource
